'use client'
import { useState,useTransition } from 'react'
import Link from 'next/link'
import { saveEventType,toggleCalendar,retryBooking,cancelBooking,blockCalendarTime,approveBookingContact } from '@/actions/calendar'
import type { ConnectedCalendar,EventType,Booking } from '@/lib/calendar/types'
import type { CalendarEntry } from '@/lib/calendar/display'
import { CalendarView } from './calendar-view'

const input='w-full rounded-lg border border-border bg-white px-3 py-2 text-sm focus-visible:outline-2 focus-visible:outline-blue-600'
const button='inline-flex min-h-11 items-center justify-center rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white disabled:opacity-50'
export function CalendarWorkspace({calendars,types,bookings,events,configured,schemaReady,syncError,appUrl,entries,anchor,today,warning,undated,contacts=[],contactsUnavailable=false,connectionFeedback,setupIssues=[],callbackUrl,recoveryUnavailable=false,recoveryLimited=false}:{calendars:ConnectedCalendar[];types:EventType[];bookings:Booking[];events:{id:string;title:string;start:string;end:string;calendar:string;allDay:boolean}[];configured:boolean;schemaReady:boolean;syncError:boolean;appUrl:string;entries:CalendarEntry[];anchor:string;today:string;warning:string;undated:number;contacts?:{id:string;name:string;email:string|null}[];contactsUnavailable?:boolean;connectionFeedback?:'success'|'error'|'configuration';setupIssues?:string[];callbackUrl?:string|null;recoveryUnavailable?:boolean;recoveryLimited?:boolean}){
 const [tab,setTab]=useState(connectionFeedback?'calendars':'calendar'),[message,setMessage]=useState(''),[pending,start]=useTransition(),[editing,setEditing]=useState<EventType|null>(null)
 const writableCalendars=calendars.filter(c=>['owner','writer'].includes(c.access_role))
 const run=(action:()=>Promise<void>,success='Cambios guardados')=>{if(pending)return;setMessage('');start(async()=>{try{await action();setMessage(success)}catch(e){setMessage(e instanceof Error?e.message:'No se pudo guardar')}})}
 return <div className="mx-auto max-w-6xl space-y-6 p-4 text-foreground sm:p-6 lg:p-10">
  <header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-muted-foreground">Tu tiempo, en un solo lugar</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Agenda</h1></div>{configured&&schemaReady?<a className={button} href="/api/calendar/google/connect">Conectar Google</a>:<button type="button" className={button} disabled aria-describedby="google-setup-reason">Conectar Google</button>}</header>
  {connectionFeedback&&<div role={connectionFeedback==='success'?'status':'alert'} className={`rounded-xl border p-4 text-sm ${connectionFeedback==='success'?'border-emerald-200 bg-emerald-50':'border-amber-200 bg-amber-50'}`}>{connectionFeedback==='success'?'Cuenta de Google conectada. Elige qué calendarios bloquean tu disponibilidad.':connectionFeedback==='configuration'?'No se pudo iniciar la conexión: completa la configuración de Google.':'No se pudo completar la conexión con Google. Si cancelaste el permiso o expiró la sesión, vuelve a conectar tu cuenta.'}</div>}
  {!schemaReady&&<p role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm">La agenda requiere activar su base de datos. Tus pagos siguen disponibles.</p>}
  {(!configured||!schemaReady)&&<div id="google-setup-reason" className="rounded-xl border border-border p-4 text-sm"><p>{!configured?'Conectar Google estará disponible cuando se configure la integración. En la vista local, Google permanece desactivado hasta que lo habilites explícitamente.':'Conectar Google estará disponible cuando la base de datos de la agenda esté preparada.'}</p>{!configured&&<details className="mt-3"><summary className="cursor-pointer font-medium">Ver requisitos de configuración</summary><ul className="mt-2 list-inside list-disc space-y-1 text-muted-foreground">{setupIssues.map(issue=><li key={issue}>{issue}</li>)}</ul>{callbackUrl&&<p className="mt-3 break-all text-xs">URI de retorno: {callbackUrl}</p>}</details>}</div>}
  <nav className="flex flex-wrap gap-1 border-b border-border pb-3" aria-label="Vistas de agenda">{[['calendar','Calendario'],['agenda','Lista de citas'],['links','Enlaces de reserva'],['calendars','Calendarios conectados']].map(([key,label])=><button key={key} onClick={()=>setTab(key)} aria-pressed={tab===key} className={`min-h-11 rounded-lg px-4 py-2 text-sm ${tab===key?'bg-secondary text-secondary-foreground':'text-zinc-600 hover:bg-zinc-100'}`}>{label}</button>)}</nav>
  {tab==='calendar'&&<CalendarView entries={entries} anchor={anchor} today={today} warning={warning} undated={undated}/>}
  {message&&<p role="status" className="rounded-lg bg-zinc-100 p-3 text-sm">{message}</p>}
  {tab==='agenda'&&<div className="space-y-6">
   <div className="flex items-center justify-between"><h2 className="font-medium">Reservas y citas por revisar</h2><button className="text-sm text-primary" onClick={()=>location.reload()}>Actualizar</button></div>
   {recoveryUnavailable&&<p role="alert" className="text-sm text-amber-800">No se pudo cargar la cola de recuperación. Actualiza la página para reintentar.</p>}
   {recoveryLimited&&<p role="status" className="text-sm text-amber-800">Se muestran las primeras 100 citas que requieren revisión.</p>}
   <p className="text-xs text-muted-foreground">La lista incluye el periodo seleccionado y las citas que requieren revisión de otros periodos. Revisa el nombre y correo del invitado antes de vincular una reserva a un contacto. La vinculación requiere tu aprobación y no concede acceso al contacto.</p>
   {!bookings.length&&schemaReady&&<p className="py-8 text-sm text-muted-foreground">Tus citas aparecerán aquí y en la ficha de cada contacto.</p>}
   <div className="divide-y divide-zinc-100">{bookings.map(b=><article key={b.id} className="space-y-3 py-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0">
      {b.client_id&&b.contact_link_status==='approved'?<Link className="font-medium text-primary" href={`/admin/clients/${b.client_id}`}>{b.guest_name}</Link>:<h3 className="break-words font-medium">{b.guest_name}</h3>}
      <p className="break-all text-xs text-muted-foreground">{b.guest_email}</p>
      <p className="mt-1 text-sm text-muted-foreground">{new Date(b.starts_at).toLocaleString('es-MX',{timeZone:'America/Monterrey'})} · Monterrey · {b.status==='confirmed'?'Confirmada':b.status==='cancelled'?'Cancelada':b.status==='cancelling'?'Cancelación en proceso':b.status==='syncing'?'Sincronizando':'Pendiente de sincronizar'}</p>
    </div><div className="flex flex-wrap gap-3">
      {['pending','sync_failed','cancelling'].includes(b.status)&&<button disabled={pending||!configured} className="min-h-11 text-sm text-primary disabled:opacity-50" onClick={()=>run(()=>retryBooking(b.id),'Solicitud de recuperación registrada. Revisa el estado de la cita.')}>{b.status==='cancelling'?'Reintentar cancelación':'Reintentar sincronización'}</button>}
      {!['cancelled','cancelling'].includes(b.status)&&<button disabled={pending} className="min-h-11 text-sm text-red-600 disabled:opacity-50" onClick={()=>{if(confirm('¿Cancelar esta cita y avisar al invitado?'))run(()=>cancelBooking(b.id),'Solicitud de cancelación registrada. Revisa el estado de la cita.')}}>Cancelar</button>}
    </div></div>
    {b.recovery_review_required?<p role="status" className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm">Esta cita requiere revisión tras {b.recovery_attempts} intentos. Revisa la conexión y utiliza el botón de reintento para continuar.</p>:b.next_retry_at&&<p className="text-xs text-muted-foreground">Próximo intento: {new Date(b.next_retry_at).toLocaleString('es-MX',{timeZone:'America/Monterrey'})} · Monterrey</p>}
    {b.contact_link_status!=='approved'&&<details className="rounded-lg border border-border p-3"><summary className="cursor-pointer text-sm font-medium">Vincular contacto · pendiente de aprobación</summary><p className="mt-2 text-xs text-muted-foreground">Verifica la identidad por un canal conocido. El correo ingresado al reservar no demuestra que sea el titular.</p>
      {contactsUnavailable?<p role="alert" className="mt-3 text-sm">No se pudieron consultar los contactos. Actualiza la página para reintentar.</p>:<form className="mt-3 flex flex-col gap-3 sm:flex-row" action={form=>run(()=>approveBookingContact(form),'Contacto vinculado con tu aprobación.')}>
        <input type="hidden" name="booking_id" value={b.id}/><label className="min-w-0 flex-1 text-sm">Contacto<select required name="client_id" defaultValue="" className={input}><option value="">Selecciona el contacto verificado</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.name}{c.email?' · '+c.email:''}</option>)}</select></label>
        <button disabled={pending||!contacts.length} className={`${button} self-start sm:self-end`}>Aprobar vinculación</button>
      </form>}
    </details>}
   </article>)}</div>
   <details className="rounded-xl border border-border p-4"><summary className="cursor-pointer text-sm font-medium">Bloquear un horario en mi calendario</summary><form className="mt-4 grid gap-3 sm:grid-cols-2" action={form=>run(async()=>{form.set('start',new Date(String(form.get('start'))).toISOString());form.set('end',new Date(String(form.get('end'))).toISOString());await blockCalendarTime(form)})}><label className="text-sm">Título<input name="title" className={input} required maxLength={120} defaultValue="Ocupado"/></label><label className="text-sm">Calendario<select className={input} name="calendar_id" required>{calendars.filter(c=>['owner','writer'].includes(c.access_role)).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-sm">Desde (hora de tu dispositivo)<input className={input} type="datetime-local" name="start" required/></label><label className="text-sm">Hasta<input className={input} type="datetime-local" name="end" required/></label><button className={button} disabled={pending||!schemaReady||!configured||!writableCalendars.length}>Guardar bloqueo</button></form></details>
   <h2 className="font-medium">En tus calendarios · periodo seleccionado</h2>
   {syncError&&<p role="alert" className="text-sm text-amber-700">No se pudo actualizar algún calendario. La disponibilidad pública se bloquea cuando no podemos verificarla.</p>}
   {events.map(e=><div key={e.id} className="border-b border-zinc-100 py-3"><p className="text-sm font-medium">{e.title}</p><p className="text-xs text-muted-foreground">{e.allDay?`${e.start} · Todo el día`:new Date(e.start).toLocaleString('es-MX',{timeZone:'America/Monterrey'})+' · Monterrey'} · {e.calendar}</p></div>)}
  </div>}
  {tab==='calendars'&&<div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><p className="max-w-xl text-sm text-muted-foreground">Conecta una o varias cuentas. Los calendarios seleccionados bloquean tus horarios; cada enlace elige dónde guardar sus reservas.</p></div>{calendars.map(c=><label key={c.id} className="flex flex-col items-start justify-between gap-4 rounded-xl border border-border p-4 sm:flex-row sm:items-center"><span className="min-w-0 break-words"><span className="block text-sm font-medium">{c.name}</span><span className="break-all text-xs text-muted-foreground">{c.google_calendar_id}</span></span><span className="flex items-center gap-2 text-sm"><input type="checkbox" checked={c.blocks_availability} disabled={pending} onChange={e=>run(()=>toggleCalendar(c.id,e.target.checked))}/>Bloquea disponibilidad</span></label>)}</div>}
  {tab==='links'&&<div className="grid gap-8 lg:grid-cols-2"><section className="space-y-4"><h2 className="font-medium">Tus enlaces</h2>{!types.length&&schemaReady&&<p className="text-sm text-muted-foreground">Crea tu primer tipo de reunión para compartir un enlace.</p>}{types.map(t=><article key={t.id} className="rounded-xl border border-border p-4"><h3 className="font-medium">{t.title}</h3><p className="mt-1 text-sm text-muted-foreground">{t.duration_minutes} min · {t.timezone} · {t.enabled?'Activo':'Pausado'}</p><div className="mt-3 flex flex-wrap gap-4 text-sm"><Link target="_blank" className="text-primary" href={`/book/${t.slug}`}>Abrir</Link><button onClick={()=>run(async()=>{await navigator.clipboard.writeText(`${appUrl||window.location.origin}/book/${t.slug}`)},'Enlace copiado')}>Copiar enlace</button><button onClick={()=>setEditing(t)}>Editar</button></div></article>)}</section>
   <section className="min-w-0"><h2 className="mb-4 font-medium">{editing?'Editar reunión':'Crear tipo de reunión'}</h2>{!writableCalendars.length&&<p className="mb-4 text-sm text-muted-foreground">Conecta un calendario con permiso para crear eventos antes de guardar un enlace.</p>}<form key={editing?.id||'new'} className="space-y-4" action={form=>run(async()=>{await saveEventType(form);setEditing(null)})}>
    {editing&&<input type="hidden" name="id" value={editing.id}/>}
    <label className="block text-sm">Nombre<input className={`${input} mt-1`} name="title" required maxLength={120} defaultValue={editing?.title} placeholder="Primera llamada"/></label>
    <label className="block text-sm">Descripción<textarea className={`${input} mt-1`} name="description" maxLength={1000} defaultValue={editing?.description}/></label>
    <label className="block text-sm">Guardar reservas en<select className={`${input} mt-1`} name="destination_calendar_id" required defaultValue={editing?.destination_calendar_id}><option value="">Selecciona calendario</option>{calendars.filter(c=>['owner','writer'].includes(c.access_role)).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label>
    <div className="grid grid-cols-2 gap-3">{[['duration_minutes','Duración (min)',15,240,30],['buffer_minutes','Margen entre citas (min)',0,120,15],['notice_hours','Anticipación (horas)',0,720,12],['horizon_days','Reservar hasta (días)',1,90,30],['start_hour','Desde (hora)',0,23,9],['end_hour','Hasta (hora)',1,24,18]].map(([key,label,min,max,value])=><label key={String(key)} className="text-sm">{label}<input className={`${input} mt-1`} type="number" name={String(key)} min={Number(min)} max={Number(max)} required defaultValue={editing?Number(editing[key as keyof EventType]):Number(value)}/></label>)}</div>
    <label className="block text-sm">Zona horaria<input className={`${input} mt-1`} name="timezone" defaultValue={editing?.timezone||'America/Monterrey'} required/></label>
    <fieldset><legend className="mb-2 text-sm">Días disponibles</legend><div className="flex flex-wrap gap-3">{['Lu','Ma','Mi','Ju','Vi','Sá','Do'].map((day,i)=><label key={day} className="flex gap-1 text-sm"><input type="checkbox" name="weekdays" value={i+1} defaultChecked={(editing?.weekdays||[1,2,3,4,5]).includes(i+1)}/>{day}</label>)}</div></fieldset>
    <label className="flex gap-2 text-sm"><input type="checkbox" name="enabled" defaultChecked={editing?.enabled??true}/>Aceptar reservas</label><button className={button} disabled={pending||!schemaReady||!configured||!writableCalendars.length}>{pending?'Guardando…':'Guardar enlace'}</button>{editing&&<button type="button" className="ml-3 text-sm" onClick={()=>setEditing(null)}>Cancelar edición</button>}
   </form></section></div>}
 </div>
}
